/ send-email.js
// Runs via GitHub Actions every morning at 8 AM IST
// Sends Apoorva her daily birthday countdown message
 
const nodemailer = require('nodemailer');
 
const START = new Date('2026-06-01T00:00:00+05:30');
 
function getTodayIST() {
  const now = new Date();
  const ist = new Date(now.toLocaleString('en-US', { timeZone: 'Asia/Kolkata' }));
  return new Date(ist.getFullYear(), ist.getMonth(), ist.getDate());
}
 
function getDayIndex() {
  const today = getTodayIST();
  const start = new Date(2026, 5, 1); // June 1 2026
  return Math.floor((today - start) / 86400000); // 0-based
}
 
// ── ALL 54 MESSAGES ──
const MESSAGES = [
  { day: 1,  date: "June 1",   subject: "Day 54 — It Begins 🐰",                    body: `My dearest Cutoo,\n\n54 days. That's how long I get to do this — send you a little piece of my heart every single morning before your birthday arrives.\n\nI don't always say the right things out loud. You know that about me. But you also know — you made me expressive. Before you, I kept everything inside. Now I have 54 days to prove it.\n\nSo here's Day 1: You have the kind of smile that doesn't just light up a room — it lights up the person looking at it. And that person, most days, is me.\n\n54 days, Cutoo. Let's make them count. 💜\n\n— Bunny 🐰` },
  { day: 2,  date: "June 2",   subject: "Day 53 — The Way You Care 💜",              body: `Cutoo,\n\nDo you know what I notice most about you?\n\nIt's not the two ponies (though yes, absolutely yes 🐰). It's that you remember things. Small things. You ask how I'm doing and actually wait for the answer. You take care of me in ways I didn't even know I needed.\n\n1.5 years of being taken care of by you — and I'm still not used to how lucky that feels.\n\n53 more days, my girl. 💜\n\n— Bunny 🐰` },
  { day: 3,  date: "June 3",   subject: "Day 52 — You're a Happy Soul ✨",           body: `Cutoo,\n\nThere's a word I keep coming back to when I think about you: radiant.\n\nNot just your smile — though that's a whole other letter's worth — but your energy. The way you walk into things with warmth. The way people around you just... feel better. That's not common. That's rare. That's you.\n\nHappy soul. That's what you are. And I'm so glad your happy soul found mine.\n\n52 days. 💜\n\n— Bunny 🐰` },
  { day: 4,  date: "June 4",   subject: "Day 51 — Mahakal 🙏",                       body: `Cutoo,\n\nI think about our Mahakal trip a lot.\n\nNot just the place — but us, there together. There's something about going somewhere sacred with someone you love that feels different. Like the universe is quietly agreeing with the two of you.\n\nI want to go back. With you. Again and again.\n\n"Har har Mahadev" — and also, har din, tum. 💜\n\n51 days, Cutoo.\n\n— Bunny 🐰` },
  { day: 5,  date: "June 5",   subject: "Day 50 — 50 Days Out 🌙",                  body: `Cutoo,\n\n50 days to your birthday.\n\nI've been trying to think of a grand thing to say but honestly? The grandest thing I know is this: being with you feels like home. Not a place — a feeling. Safe. Warm. Real.\n\nSome people spend their whole lives looking for that. I found it in you.\n\n50 days. 💜\n\n— Bunny 🐰` },
  { day: 6,  date: "June 6",   subject: "Day 49 — Two Ponies 🐰",                   body: `Cutoo,\n\nOkay, today's letter is short because it's about something very important:\n\nThe two ponies.\n\nI don't make the rules. It's just objectively the cutest thing. Every single time. Without fail.\n\nThat's it. That's the whole letter. You already know. 🐰💜\n\n49 days!\n\n— Bunny` },
  { day: 7,  date: "June 7",   subject: "Day 48 — One Week In 💌",                  body: `Cutoo,\n\nOne week of letters. 47 more to go.\n\nHere's what I want you to know at the one-week mark: I'm not doing this because I have to. I'm doing this because when I imagine your face reading these every morning — that makes me happy in a way I can't quite explain.\n\nYou deserve to be celebrated. Every. Single. Day. Not just on July 25th.\n\n48 days. 💜\n\n— Bunny 🐰` },
  { day: 8,  date: "June 8",   subject: "Day 47 — What You've Given Me 🌸",         body: `Cutoo,\n\nYou made me expressive.\n\nI want to sit with that for a moment because it's one of the most significant things anyone has ever done for me.\n\nBefore you, I didn't know how to say the soft things. The real things. The "I'm scared" and "I miss you" and "this matters to me" things.\n\nYou didn't push. You just... made it safe. And slowly, I learned.\n\nThank you. For that, more than almost anything.\n\n47 days. 💜\n\n— Bunny 🐰` },
  { day: 9,  date: "June 9",   subject: "Day 46 — Good Morning, Cutoo ☀️",          body: `Cutoo,\n\nGood morning.\n\nI just wanted to say that today, like every day, the world is a little better because you're in it. Not metaphorically. Actually.\n\nGo have a beautiful day. Drink water. Eat something good. Smile at someone. You're going to be great today — you always are.\n\n46 days. 💜\n\n— Bunny 🐰` },
  { day: 10, date: "June 10",  subject: "Day 45 — You Don't Even Know 💜",          body: `Cutoo,\n\n"You don't even know you're beautiful" — Harry Styles wrote that but honestly, it describes you perfectly.\n\nThe way you carry yourself. The way you laugh. The way you don't try to be anything other than exactly what you are — and what you are is wonderful.\n\nI know it. Even when you don't.\n\n45 days. 💜\n\n— Bunny 🐰` },
  { day: 11, date: "June 11",  subject: "Day 44 — The Little Things 🌙",            body: `Cutoo,\n\nIt's the little things I remember most:\n\nThe way you check on me. The ponies. Your laugh when something genuinely catches you off guard. The way you say my name.\n\nThese aren't big moments. But they're the ones that I carry with me everywhere.\n\n44 days. 💜\n\n— Bunny 🐰` },
  { day: 12, date: "June 12",  subject: "Day 43 — Nice Person 💐",                  body: `Cutoo,\n\n"Nice person" sounds simple. But it's actually one of the rarest things.\n\nGenuinely nice. Not nice because it's convenient. Not nice when people are watching. Just... consistently, quietly, warmly good to the people around her.\n\nThat's you. And the world needs more of you, honestly.\n\n43 days. 💜\n\n— Bunny 🐰` },
  { day: 13, date: "June 13",  subject: "Day 42 — 42 💫",                            body: `Cutoo,\n\nFun fact: 42 is supposedly "the answer to life, the universe and everything."\n\nMy answer to life, the universe and everything is considerably cuter and has two ponies.\n\n42 days. 💜\n\n— Bunny 🐰` },
  { day: 14, date: "June 14",  subject: "Day 41 — Two Weeks 🕯️",                   body: `Cutoo,\n\nTwo weeks of letters.\n\nI want to ask you something today: what's one thing you're excited about? Not about your birthday — just in general. About life, about us, about anything.\n\nI ask because I love knowing what lights you up.\n\nTell me today. 💜\n\n41 days.\n\n— Bunny 🐰` },
  { day: 15, date: "June 15",  subject: "Day 40 — 40 Days Out 🌸",                  body: `Cutoo,\n\n40 days.\n\nSomewhere between the first letter and this one, something shifted a little. These aren't just countdown messages anymore. They're just... me, talking to you. Every morning. Like I would if I could.\n\nI hope they feel that way to you too.\n\n40 days. 💜\n\n— Bunny 🐰` },
  { day: 16, date: "June 16",  subject: "Day 39 — Be Together Always 🌙",           body: `Cutoo,\n\n"Be together always" — that's our dream, isn't it?\n\nNot a complicated one. Not a dramatic one. Just: always. Through the ordinary Tuesdays and the extraordinary moments and everything in between.\n\nI'm in. Completely. Are you? (I already know the answer. I just like saying it.)\n\n39 days. 💜\n\n— Bunny 🐰` },
  { day: 17, date: "June 17",  subject: "Day 38 — You Take Care of Me 💜",          body: `Cutoo,\n\nThere's something about being cared for by the person you love — it stays with you differently than any other kindness. It becomes part of you.\n\nYou're part of me, Cutoo. In the best possible way.\n\n38 days. 💜\n\n— Bunny 🐰` },
  { day: 18, date: "June 18",  subject: "Day 37 — A Song for You 🎵",               body: `Cutoo,\n\n"I found a love for me\nDarling just dive right in, follow my lead\nWell I found a girl, beautiful and sweet\nI never knew you were the someone waiting for me"\n\n— Ed Sheeran knew. 💜\n\n37 days.\n\n— Bunny 🐰` },
  { day: 19, date: "June 19",  subject: "Day 36 — Your Smile 😊",                   body: `Cutoo,\n\nYour smile is genuinely one of my favourite things in the world.\n\nNot the polite smile. Not the camera smile. The real one — the one that scrunches your nose a little, the one that comes out when something actually delights you.\n\nI spend a lot of time trying to be the reason for that smile.\n\n36 days. 💜\n\n— Bunny 🐰` },
  { day: 20, date: "June 20",  subject: "Day 35 — Past the Halfway 🌟",             body: `Cutoo,\n\nMore than halfway through June now.\n\nTime moves differently when you're looking forward to something. These 54 days feel both long and impossibly short. I want July 25th to come. I also want to keep writing you these letters forever.\n\nMaybe I'll do both. 💜\n\n35 days.\n\n— Bunny 🐰` },
  { day: 21, date: "June 21",  subject: "Day 34 — Three Weeks 🌙",                  body: `Cutoo,\n\nThree weeks of letters.\n\nToday I just want to say: I'm proud of you. For everything you carry with grace. For every hard day you got through. For the person you've become and keep becoming.\n\nYou're doing great, even on the days it doesn't feel like it.\n\n34 days. 💜\n\n— Bunny 🐰` },
  { day: 22, date: "June 22",  subject: "Day 33 — What I Remember Most 💭",        body: `Cutoo,\n\nI always remember you.\n\nNot just big things — but you, specifically. The version of you that's tired but still kind. The version that laughs at things she's not supposed to. The version that keeps showing up.\n\nI always remember her. I always will.\n\n33 days. 💜\n\n— Bunny 🐰` },
  { day: 23, date: "June 23",  subject: "Day 32 — Future Plans 🌏",                 body: `Cutoo,\n\nI think about our future like a map with so many pins in it. Places to see. Things to eat. Mornings in cities we've never been. Nights under skies we haven't seen yet.\n\nI want all of it. With you.\n\n32 days. 💜\n\n— Bunny 🐰` },
  { day: 24, date: "June 24",  subject: "Day 31 — Almost July 🎉",                  body: `Cutoo,\n\nAlmost July. Almost your month.\n\nDid you know that July is named after Julius Caesar? He didn't have a cute birthday countdown though. Clearly he had his priorities wrong.\n\nYou have me. Much better. 💜\n\n31 days!\n\n— Bunny 🐰` },
  { day: 25, date: "June 25",  subject: "Day 30 — One Month Out 🥂",                body: `Cutoo,\n\nONE MONTH. 30 days until your birthday.\n\nIn one month, you complete another year of being wonderful. One more year of that smile, those ponies, that warm heart.\n\nI'm going to celebrate you so well. Just wait.\n\n30 days. 💜🎉\n\n— Bunny 🐰` },
  { day: 26, date: "June 26",  subject: "Day 29 — You Make Me Better 💜",           body: `Cutoo,\n\nCan I tell you something I don't say enough?\n\nYou make me better. Not by pushing. Just by being the kind of person who makes you want to be more — more present, more expressive, more int
